service: simple-todo

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 128

functions:
  getTodos:
    handler: handler.getTodos
    events:
      - http:
          path: api/v1/todos
          method: get
          cors: true
  getTodoById:
    handler: handler.getTodoById
    events:
      - http:
          path: api/v1/todos/{id}
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
